# Generated by Django 5.0.2 on 2024-02-24 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('technicians', '0001_initial'),
        ('tickets', '0008_ticket_assigned_to'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Technicians',
            new_name='Technician',
        ),
    ]
