# Generated by Django 5.0.2 on 2024-02-26 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0005_alter_customer_department_alter_customer_ext_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComputerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('processor', models.CharField(blank=True, help_text='In GHz(e.g.:i5 2.9 GHz)', max_length=100, null=True)),
                ('ram', models.IntegerField(help_text='In GB', verbose_name='RAM')),
                ('hdd', models.IntegerField(help_text='In GB', verbose_name='HDD/Storage')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ComputerType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('details', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Maker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True)),
                ('date_received', models.DateField(blank=True, null=True)),
                ('date_installed', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['model__name'],
            },
        ),
        migrations.CreateModel(
            name='OperatingSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Statuses',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True)),
                ('warranty_info', models.CharField(max_length=100, verbose_name='Warranty')),
                ('computer_name', models.CharField(blank=True, max_length=100, null=True)),
                ('ip_addr', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('user', models.CharField(blank=True, max_length=100, null=True)),
                ('date_received', models.DateField(blank=True, null=True)),
                ('date_installed', models.DateField(blank=True, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='system_audit/')),
                ('notes', models.TextField(blank=True, null=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='computer_departments', to='customers.department')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='computers', to='assets.computermodel')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='computer_locations', to='assets.location')),
                ('monitor', models.ManyToManyField(blank=True, related_name='monitors', to='assets.monitor')),
                ('os', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.operatingsystem', verbose_name='Operating System')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.status')),
            ],
            options={
                'ordering': ['computer_name'],
            },
        ),
        migrations.CreateModel(
            name='ComputerComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('computer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='assets.computer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='computermodel',
            name='computer_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.computertype'),
        ),
        migrations.AddField(
            model_name='computermodel',
            name='maker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.maker'),
        ),
        migrations.CreateModel(
            name='MonitorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.FileField(blank=True, null=True, upload_to='monitor_models/')),
                ('maker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.maker')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='monitor',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitors', to='assets.monitormodel'),
        ),
        migrations.CreateModel(
            name='PrinterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.FileField(blank=True, null=True, upload_to='printer_models/')),
                ('maker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.maker')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True)),
                ('printer_name', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('ip_addr', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('dept', models.CharField(blank=True, max_length=100, null=True, verbose_name='Department')),
                ('date_received', models.DateField(blank=True, null=True)),
                ('date_installed', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='printer_departments', to='customers.department')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='printer_sites', to='assets.location', verbose_name='location')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='printers', to='assets.printermodel')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.status')),
            ],
            options={
                'ordering': ['ip_addr'],
            },
        ),
        migrations.AddField(
            model_name='monitor',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assets.status'),
        ),
    ]
