# Generated by Django 5.0.2 on 2024-02-12 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComputerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('processor', models.CharField(max_length=100)),
                ('ram', models.IntegerField(help_text='In GB', verbose_name='RAM')),
                ('hdd', models.IntegerField(help_text='In GB')),
            ],
        ),
        migrations.CreateModel(
            name='ComputerType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Maker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=100)),
                ('computer_name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('ip_addr', models.GenericIPAddressField(blank=True, null=True)),
                ('dept', models.CharField(max_length=100)),
                ('user', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('date_received', models.DateField(blank=True, null=True)),
                ('date_installed', models.DateField(blank=True, null=True)),
                ('warranty_info', models.CharField(max_length=100)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.computermodel')),
            ],
        ),
        migrations.AddField(
            model_name='computermodel',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.computertype'),
        ),
        migrations.AddField(
            model_name='computermodel',
            name='maker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.maker'),
        ),
        migrations.AddField(
            model_name='computermodel',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.status'),
        ),
    ]
