# Generated by Django 5.0.2 on 2024-02-28 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='printer',
            name='site',
        ),
        migrations.AddField(
            model_name='printer',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='printer_locations', to='assets.location'),
        ),
    ]
