# Generated by Django 5.0.2 on 2024-02-28 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='printer',
            name='location',
        ),
    ]
