# Generated by Django 5.0.2 on 2024-02-12 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='computermodel',
            name='status',
        ),
        migrations.AlterField(
            model_name='computer',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.status'),
        ),
    ]
