# Generated by Django 5.0.2 on 2024-03-06 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComputerName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('computer_name', models.CharField(max_length=100)),
                ('last_used_number', models.IntegerField(default=0, editable=False)),
            ],
        ),
    ]
