# Generated by Django 5.0.2 on 2024-03-05 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='assets.project'),
        ),
    ]
