# Generated by Django 5.0.2 on 2024-03-06 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_computername'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computername',
            name='last_used_number',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
