# Generated by Django 5.0.2 on 2024-02-12 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_remove_computermodel_status_alter_computer_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='computermodel',
            old_name='type',
            new_name='computer_type',
        ),
        migrations.AlterField(
            model_name='computer',
            name='computer_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='computer',
            name='dept',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='computer',
            name='serial_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='computer',
            name='user',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='computermodel',
            name='processor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
