# Generated by Django 5.0.2 on 2024-02-28 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_printer_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='MicrosoftOfficeVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='MicrosoftOffice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_key', models.CharField(max_length=30, unique=True)),
                ('date_installed', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('computer_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assets.computer')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='assets.microsoftofficeversion')),
            ],
            options={
                'ordering': ['-date_installed'],
            },
        ),
    ]
