# Generated by Django 5.0.2 on 2024-02-12 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_rename_type_computermodel_computer_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='computers', to='assets.computermodel'),
        ),
        migrations.AlterField(
            model_name='computermodel',
            name='hdd',
            field=models.IntegerField(help_text='In GB', verbose_name='HDD/Storage'),
        ),
        migrations.AlterField(
            model_name='computermodel',
            name='processor',
            field=models.CharField(blank=True, help_text='In GHz(e.g.:i5 2.9 GHz)', max_length=100, null=True),
        ),
    ]
