# Generated by Django 5.0.2 on 2024-02-26 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_project_computer_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='computer',
            name='ip_addr',
        ),
        migrations.AlterField(
            model_name='computercomment',
            name='comment',
            field=models.TextField(null=True),
        ),
    ]
