# Generated by Django 5.0.2 on 2024-02-27 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_remove_computer_ip_addr_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitor',
            name='status',
        ),
    ]
