# Generated by Django 5.0.2 on 2024-02-28 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_alter_microsoftoffice_date_installed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='microsoftoffice',
            old_name='computer_name',
            new_name='computer',
        ),
    ]
