# Generated by Django 5.0.2 on 2024-03-12 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_alter_computername_computer_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ComputerName',
        ),
    ]
