# Generated by Django 5.0.2 on 2024-02-13 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_alter_status_options_printermodel_printer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='printer',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
