# Generated by Django 5.0.2 on 2024-02-13 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_alter_computer_location_alter_printer_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='printer',
            old_name='computer_name',
            new_name='printer_name',
        ),
    ]
