# Generated by Django 5.0.2 on 2024-02-28 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0007_microsoftoffice_is_installed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='microsoftoffice',
            name='computer',
            field=models.ForeignKey(blank=True, help_text='serial number', null=True, on_delete=django.db.models.deletion.CASCADE, to='assets.computer'),
        ),
    ]
