# Generated by Django 5.0.2 on 2024-02-28 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0008_alter_microsoftoffice_computer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='microsoftoffice',
            name='computer',
            field=models.ForeignKey(blank=True, help_text='serial number', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='office_installations', to='assets.computer'),
        ),
    ]
