# Generated by Django 5.0.2 on 2024-02-13 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0008_operatingsystem_computer_os'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='os',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.operatingsystem', verbose_name='Operating System'),
        ),
    ]
