# Generated by Django 5.0.2 on 2024-02-29 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0009_alter_microsoftoffice_computer'),
    ]

    operations = [
        migrations.AddField(
            model_name='microsoftoffice',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
