# Generated by Django 5.0.2 on 2024-02-13 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0009_alter_computer_os'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='system_audit/'),
        ),
    ]
