# Generated by Django 5.0.2 on 2024-02-13 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0010_computer_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='ip_addr',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address'),
        ),
    ]
