# Generated by Django 5.0.2 on 2024-02-29 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0010_microsoftoffice_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='microsoftoffice',
            name='has_failed',
            field=models.BooleanField(default=False),
        ),
    ]
