# Generated by Django 5.0.2 on 2024-02-14 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0011_alter_computer_ip_addr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='computer',
            old_name='file',
            new_name='image',
        ),
        migrations.AddField(
            model_name='printermodel',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='system_audit/'),
        ),
    ]
