# Generated by Django 5.0.2 on 2024-02-14 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0012_rename_file_computer_image_printermodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printermodel',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='printer_models/'),
        ),
    ]
