# Generated by Django 5.0.2 on 2024-02-14 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0013_alter_printermodel_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='printer',
            name='warranty_info',
        ),
        migrations.AddField(
            model_name='computer',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='printer',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
