# Generated by Django 5.0.2 on 2024-02-14 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0015_monitormodel_monitor'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='monitor',
            field=models.ManyToManyField(related_name='monitors', to='assets.monitor'),
        ),
    ]
