# Generated by Django 5.0.2 on 2024-02-16 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0018_alter_computer_options_alter_computermodel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='dept',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='warranty_info',
            field=models.CharField(max_length=100, verbose_name='Warranty'),
        ),
        migrations.AlterField(
            model_name='printer',
            name='dept',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='printer',
            name='ip_addr',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address'),
        ),
    ]
