# Generated by Django 5.0.2 on 2024-02-23 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0021_alter_computercomment_computer'),
        ('customers', '0005_alter_customer_department_alter_customer_ext_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customers.department', verbose_name='departments'),
        ),
        migrations.AddField(
            model_name='printer',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customers.department', verbose_name='departments'),
        ),
    ]
