# Generated by Django 5.0.2 on 2024-02-23 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0022_computer_department_printer_department'),
        ('customers', '0005_alter_customer_department_alter_customer_ext_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='computer_departments', to='customers.department'),
        ),
        migrations.AlterField(
            model_name='printer',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='printer_departments', to='customers.department'),
        ),
    ]
