# Generated by Django 5.0.2 on 2024-02-26 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0024_location_computer_site_monitor_site_printer_site'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitor',
            name='dept',
        ),
        migrations.RemoveField(
            model_name='monitor',
            name='location',
        ),
        migrations.RemoveField(
            model_name='monitor',
            name='monitor_name',
        ),
        migrations.RemoveField(
            model_name='monitor',
            name='site',
        ),
        migrations.AlterField(
            model_name='monitor',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assets.status'),
        ),
    ]
