# Generated by Django 5.0.2 on 2024-02-26 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0025_remove_monitor_dept_remove_monitor_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='computer',
            name='dept',
        ),
        migrations.AlterField(
            model_name='computer',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='computer_locations', to='assets.location'),
        ),
    ]
