# Generated by Django 5.0.2 on 2024-02-26 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0027_remove_computer_site'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='computer',
            name='location',
        ),
    ]
