# Generated by Django 5.0.2 on 2024-02-14 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='customer',
            name='department',
        ),
    ]
