# Generated by Django 5.0.2 on 2024-02-14 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_customer_options_remove_customer_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.department'),
        ),
    ]
