# Generated by Django 5.0.2 on 2024-02-14 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_customer_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='job_title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
