# Generated by Django 5.0.2 on 2024-03-06 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_ticketcategory_ticketstatus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticketstatus',
            options={'ordering': ['name'], 'verbose_name_plural': 'Ticket Statuses'},
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticket_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tickets.ticketcategory'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticket_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tickets.ticketstatus'),
        ),
    ]
