# Generated by Django 5.0.2 on 2024-03-06 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_alter_ticketstatus_options_ticket_ticket_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tickets.ticketcategory', verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tickets.ticketstatus', verbose_name='status'),
        ),
    ]
