# Generated by Django 5.0.2 on 2024-02-14 18:38

import tickets.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_ticket_ticket_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_id',
            field=models.CharField(default=tickets.models.generate_short_id, editable=False, max_length=8, unique=True),
        ),
    ]
