# Generated by Django 5.0.2 on 2024-02-19 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_comment_created_at_alter_comment_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='slug',
            field=models.SlugField(blank=True, max_length=8, null=True, unique=True),
        ),
    ]
