# Generated by Django 5.0.2 on 2024-02-26 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0009_alter_ticket_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='summary',
            field=models.CharField(default='Summary', max_length=100),
        ),
    ]
