# Generated by Django 5.0.2 on 2024-02-27 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0010_ticket_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='tickets/'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='summary',
            field=models.CharField(max_length=100),
        ),
    ]
