# Generated by Django 5.0.2 on 2024-02-27 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0011_ticket_image_alter_ticket_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='image',
            new_name='file',
        ),
    ]
